version: "3.0"

services: 
    master1: 
        image: mysql/mysql-server:5.7.17
        volumes:
            - /root/mysql-replication/master-master/master1/conf:/etc/mysql
            - /root/mysql-replication/master-master/master1/data:/var/lib/mysql
        expose:
            - "3306"
        environment: 
            - MYSQL_ROOT_PASSWORD=123456
    
    master2:
        image: mysql/mysql-server:5.7.17
        volumes:
            - /root/mysql-replication/master-master/master2/conf:/etc/mysql 
            - /root/mysql-replication/master-master/master2/data:/var/lib/mysql
        expose:
            - "3306"    
        environment:
            - MYSQL_ROOT_PASSWORD=123456
